name: connected
description:  Flutter package for build real internet connection notifier on widget tree.
version: 0.1.1+17
homepage: https://github.com/sohrabonline/connected

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #internet_connection_checker_plus: ^2.0.0
  dio: ^5.7.0
  connectivity_plus: ^6.1.0
#  internet_connection_checker_plus:
#    path: ../internet_connection_checker_plus


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
